language: node_js
node_js:
- 10.15.1
cache:
  directories:
  - node_modules
branches:
  only:
  - main
  - staging
before_script:
- npm install
script:
- if [[ "$TRAVIS_BRANCH" = "main" || "$TRAVIS_BRANCH" = "staging" ]]; then npm run
  build; else echo "not a build branch"; fi
before_deploy:
- cd $TRAVIS_BUILD_DIR
- sed -i '/dist/d' .gitignore
- git add . && git commit -m "latest build"
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIASIYNIY4ZGQUHGZM5
  secret_access_key:
    secure: VHKK6+PjNJ9Fvg5jLt3P1sMZy+VYqOL3+uU6FUH7duV/tFy2ZZWJRqg+pzCW3uuc9e3sojvX2NfB6YGRbYK5R5t7ABQbshTHqpxQiD6OAQcui4WuF1EGOyGVRFgbQwfX6N0yypDCC6OAJtqoTh9FGSrz5mws8x61COkP/0W1QvSGW9GSDdtteUvEqbC0rHPVa+YLkCVyCMuuw69Nw4yO4Lxj7eLIN5AY1gPw9DCT/JxUhmiBO8dlCx/Hi4trwsz2jYQbK0gUOSVVoP3yaklPRBYeMXZKrqZgJLQjithm7I7Am6TYRhitnI8Qq71Nw9n6x7gPguJbhYOs67sG2CbGgyT+NVGY65l2n/l+wpCXh6fAV4iy1RiIs0795NAviBNX55awb9fV6L78I5xRqLehlcP/GTp3ntNOFhe8Xau0lBf2ILY9eYO8U76iqfElGlcI4eQpnKzcPE6NCTOQ0lsB0yqiQLmFn81Hxpi0/xUXsg+46s9jnxugiM6yQgrtUp6wnRciIg3N8TE+qkqP/CCJVpRzYhJ0nqd0HalVWYS8FPRM+MVLfZzLKgRFK0wM9Cvt8ahdt5T15HVS66eP7X95VYfd8Brfb1wOe1suKZL4GJGJ/7lF4nRs8lviBRQOY8O1wsA4rLVM/4HIe9CqzA52ppHMz+OjmOBaQQkay6Z4Qk0=
  region: ap-southeast-1
  app: Synchrony
  env: Synchrony-env
  bucket_name: elasticbeanstalk-ap-southeast-1-156257273650
  on:
    repo: simshengqin/Synchrony-Development
    branch: main
  skip_cleanup: 'true'
after_deploy:
- echo "Applcation Deployed!"
env:
  global:
    secure: c1DVtJ0+NchJSgPcq5HlI63ki3WCKQiwcBnhW6JDEoKC3zacFJh87dtNpJPeZ/xrTryMmU+HX//NzY53+SkKD8PxibIkBF8ddIZqOPBs/5uwTnPWOBCopyFTi/P9y57x4InkKC3bk2kB4nlNTnIDZ7xXVVO6Tmj3Xm4HBpAAvUxhVOiMCCMgYgVnGFjHpiuBWI4ZteJfEmYJOlZOCIPpRiPfnOQmWT4qhLFIJ6ZUxaJzeFchDZEVthCB9cwPKmz1yjOp8h9AkkZ82ZcTWMU4OSBV69GE4fpl3fz55mdz4nK1KGDaTSUDupRK/lN9bketiU+ivdbxn0bzhjUc2ghAkB22naPQTIs/Lzws7GL7PGnNeXboTpaovzhHKw6YqbszZRKRNqzfQDt3sFy49hDiXmwTBLSVOl5Fuk3+ZxTWgVBWO6Mw7pSvVET57EMVvCFmfh2ogNzA1B6nQTuno8UF5/CuSeib4weIqZ6MA/s6a4VSjXxxAsTfgiuC778KhHoZTPWhvML5JO+TTaozcM2IKQDS7KG1P2amRAb4ambJOAw94myFYUSZtM68dAPyJYHlo6XadfbtlFt6D9zByh0ubxpPsc+M2zCTqV4dxemN8xh4JGkipE8mMdZuT8rVa1VGfe7n9lle1fcC10YNz85NmjdJGSKfL57pqxAuw/lqAsE=
