language: node_js

node_js:
  - 10.15.1

cache:
  directories:
    - node_modules

branches:
  only:
    - staging
    - main

before_script:
  - npm install

script:
  - if [[ "$TRAVIS_BRANCH" = "main" || "$TRAVIS_BRANCH" = "staging" ]]; then npm run build; else echo "not a build branch"; fi

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - sed -i '/dist/d' .gitignore
  - git add . && git commit -m "latest build"
  
deploy: 
  access_key_id: 
    secure: "Encrypted <access-key-id>=AKIASIYNIY4ZGQUHGZM5"
  app: Synchrony
  bucket_name: elasticbeanstalk-ap-southeast-1-156257273650
  env: Synchrony-env
  provider: elasticbeanstalk
  region: ap-southeast-1
  secret_access_key: 
    secure: "Encypted <secret-access-key>=POQp6NLntdsQngA00zoHuUoVMDllqG+OXHOA45zk"
  on:
    branches:    
      only:      
        - master 
after_deploy:
  - echo "Applcation Deployed!"