language: node_js

node_js:
  - 10.15.1

cache:
  directories:
    - node_modules

branches:
  only:
    - staging
    - main

before_script:
  - npm install

script:
  - if [[ "$TRAVIS_BRANCH" = "master" || "$TRAVIS_BRANCH" = "staging" ]]; then npm run build; else echo "not a build branch"; fi

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - sed -i '/dist/d' .gitignore
  - git add . && git commit -m "latest build"
  
deploy:
  - provider: elasticbeanstalk
    access_key_id: AKIASIYNIY4ZGQUHGZM5            // You have use environment variable name instead of plain text
    secret_access_key: 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     // You have use environment variable name instead of plain text
    region: "ap-southeast-1"            // "ap-south-1"
    app: "demo-application"                     // "demo-application"
    env: "demo-production"                     // "demo-production"
    bucket_name: "elasticbeanstalk-ap-southeast-1-156257273650" // Once you create new application, it will automatically create a unique bucket for it.
    on:
      branch: main // For example: - master

after_deploy:
  - echo "Applcation Deployed!"